samples: data/samples.tsv

alevin:
  # transcript to gene map tsv file (--tgMap)
  tgmap: /ifs/mirror/alevin/txp2gene.tsv
  # salmon index
  index: /ifs/mirror/alevin/salmon_partial_sa_index
  # misc
  threads: 16
  memory_gb: 64